#!/bin/csh

## ---
## This shell script performs the commands
## that are suggested in the READ_ME file.
##

   cc -v -o pgm1 pgm1.c
   cc -v -o pgm2 pgm2.c
   cc -v -o overlay main.c
   overlay

   rm -f pgm1 pgm2 overlay
