#include <iostream.h>

int main()
{
   cout << "\n"
           "---\n"
           "What looks right on one screen\n"
           "may not look right on another.\n"
           "Here is another large I.\n"
           "\n"
           "\n"
           "                                   IIIIIIIIIII\n"
           "                                   IIIIIIIIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                      IIIII\n"
           "                                   IIIIIIIIIII\n"
           "                                   IIIIIIIIIII\n"
           "\n"
           "\n";
}
